name: laba_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  cached_network_image: ^3.3.0
  dashed_line: ^0.1.0
  sealed_currencies: ^0.2.2
  sliver_tools: ^0.2.12
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.1.0
  custom_lint: ^0.5.3
  build_runner: ^2.4.6
  freezed: ^2.4.5


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: San Francisco Pro Text
      fonts:
        - asset: fonts/sf_pro_text_bold.ttf
          weight: 600
        - asset: fonts/sf_pro_text_medium.ttf
          weight: 500
    - family: San Francisco Pro Display
      fonts:
        - asset: fonts/sf_pro_display_bold.otf
          weight: 600
flutter_assets_generator:
  output_dir: src\shared\assets