///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsArrowRight = 'assets/icons/arrow_right.svg';
  static const String iconsClose = 'assets/icons/close.svg';
  static const String iconsIarrowsForwardBack = 'assets/icons/iarrows_forward_back.svg';
  static const String iconsIc36PercentFill = 'assets/icons/ic_36_percent_fill.svg';
  static const String iconsLogOut = 'assets/icons/log_out.svg';
  static const String iconsMc36Sberprime = 'assets/icons/mc_36_sberprime.svg';
  static const String iconsPercent = 'assets/icons/percent.svg';
  static const String iconsPressure = 'assets/icons/pressure.svg';
  static const String imagesUserPhoto = 'assets/images/user_photo.png';

}
